### ISSUE TITLE
Migration tracking

### ISSUE THREAD

**Issue by tristanlatr** [LesFruitsDefendus/guides#7]
- [x] [Pre-Pick Guide](https://lesfruitsdefendus.readthedocs.io/fr/latest/pre-pick-guide/index.html)
- [x] [Support for Pickleaders](https://lesfruitsdefendus.readthedocs.io/fr/latest/pre-pick-guide/support-for-pickleaders.html)
- [x] [Life Cycle of a Pick on Saskatoon](https://lesfruitsdefendus.readthedocs.io/fr/latest/pre-pick-guide/life-cycle-of-a-pick-on-saskatoon.html)
- [x] [Planning a harvest](https://lesfruitsdefendus.readthedocs.io/fr/latest/pre-pick-guide/planning-a-harvest.html)
- [x] [Annexes](https://lesfruitsdefendus.readthedocs.io/fr/latest/pre-pick-guide/annexes/index.html)
- [x] [Beneficiary organizations](https://lesfruitsdefendus.readthedocs.io/fr/latest/pre-pick-guide/annexes/A-beneficiary-organizations.html)
- [x] [Fruit ripeness](https://lesfruitsdefendus.readthedocs.io/fr/latest/pre-pick-guide/annexes/C-fruit-ripeness.html)
- [x] [Planning Harvests using the Properties List](https://lesfruitsdefendus.readthedocs.io/fr/latest/pre-pick-guide/annexes/D-using-the-property-list.html)
- [x] [Script for Contacting the Tree-Owner and Editing Property Information](https://lesfruitsdefendus.readthedocs.io/fr/latest/pre-pick-guide/annexes/E-tree-owner-script-update.html)
- [x] [Harvest Guide](https://lesfruitsdefendus.readthedocs.io/fr/latest/harvest-guide/index.html)
- [x] [Retrieve equipment and bring it to the pick site](https://lesfruitsdefendus.readthedocs.io/fr/latest/harvest-guide/pick-equipment.html)
- [x] [Prepare for the pick](https://lesfruitsdefendus.readthedocs.io/fr/latest/harvest-guide/prepare-for-the-pick.html)
- [x] [Welcoming the volunteer pickers](https://lesfruitsdefendus.readthedocs.io/fr/latest/harvest-guide/welcome-volunteer-pickers.html)
- [x] [How to harvest and store fruit](https://lesfruitsdefendus.readthedocs.io/fr/latest/harvest-guide/how-to-harvest.html)
- [x] [Supervise the harvest](https://lesfruitsdefendus.readthedocs.io/fr/latest/harvest-guide/supervise-harvest.html)
- [x] [What to do in difficult situations?](https://lesfruitsdefendus.readthedocs.io/fr/latest/harvest-guide/difficult-situations.html)
- [x] [Deliver the fruits to the beneficiary and return the equipment to the storage site](https://lesfruitsdefendus.readthedocs.io/fr/latest/harvest-guide/complete-the-pick.html)
- [x] [Record your pick data in Saskatoon](https://lesfruitsdefendus.readthedocs.io/fr/latest/harvest-guide/record-data-in-saskatoon.html)
- [x] [Annexes](https://lesfruitsdefendus.readthedocs.io/fr/latest/harvest-guide/annexes/index.html)
- [x] [Information on bike safety and the trailer](https://lesfruitsdefendus.readthedocs.io/fr/latest/harvest-guide/annexes/1-bike-safety.html)
- [x] [Ladder Security](https://lesfruitsdefendus.readthedocs.io/fr/latest/harvest-guide/annexes/2-ladder-security.html)
- [x] [Complementary information - Health and security](https://lesfruitsdefendus.readthedocs.io/fr/latest/harvest-guide/annexes/3-complementary-infos.html)
- [x] [Contacting other members of the collective](https://lesfruitsdefendus.readthedocs.io/fr/latest/harvest-guide/annexes/5-contacting-other-members-of-the-collective.html)

**Comment by lesfruits** [comment]
i will migrate [Beneficiary organizations](https://lesfruitsdefendus.readthedocs.io/fr/latest/pre-pick-guide/annexes/A-beneficiary-organizations.html)

**Comment by lesfruits** [comment]
i will do the whole pre pick guide and harvest guide!
