### ISSUE TITLE
Translation tracking

### ISSUE THREAD

**Issue by tristanlatr** [LesFruitsDefendus/guides#8]
- [ ] [Pre-Pick Guide](https://lesfruitsdefendus.readthedocs.io/fr/latest/pre-pick-guide/index.html)
- [ ] [Support for Pickleaders](https://lesfruitsdefendus.readthedocs.io/fr/latest/pre-pick-guide/support-for-pickleaders.html)
- [ ] [Life Cycle of a Pick on Saskatoon](https://lesfruitsdefendus.readthedocs.io/fr/latest/pre-pick-guide/life-cycle-of-a-pick-on-saskatoon.html)
- [ ] [Planning a harvest](https://lesfruitsdefendus.readthedocs.io/fr/latest/pre-pick-guide/planning-a-harvest.html)
- [ ] [Annexes](https://lesfruitsdefendus.readthedocs.io/fr/latest/pre-pick-guide/annexes/index.html)
- [ ] [Beneficiary organizations](https://lesfruitsdefendus.readthedocs.io/fr/latest/pre-pick-guide/annexes/A-beneficiary-organizations.html)
- [ ] [Fruit ripeness](https://lesfruitsdefendus.readthedocs.io/fr/latest/pre-pick-guide/annexes/C-fruit-ripeness.html)
- [ ] [Planning Harvests using the Properties List](https://lesfruitsdefendus.readthedocs.io/fr/latest/pre-pick-guide/annexes/D-using-the-property-list.html)
- [ ] [Script for Contacting the Tree-Owner and Editing Property Information](https://lesfruitsdefendus.readthedocs.io/fr/latest/pre-pick-guide/annexes/E-tree-owner-script-update.html)
- [ ] [Harvest Guide](https://lesfruitsdefendus.readthedocs.io/fr/latest/harvest-guide/index.html)
- [ ] [Retrieve equipment and bring it to the pick site](https://lesfruitsdefendus.readthedocs.io/fr/latest/harvest-guide/pick-equipment.html)
- [ ] [Prepare for the pick](https://lesfruitsdefendus.readthedocs.io/fr/latest/harvest-guide/prepare-for-the-pick.html)
- [ ] [Welcoming the volunteer pickers](https://lesfruitsdefendus.readthedocs.io/fr/latest/harvest-guide/welcome-volunteer-pickers.html)
- [ ] [How to harvest and store fruit](https://lesfruitsdefendus.readthedocs.io/fr/latest/harvest-guide/how-to-harvest.html)
- [ ] [Supervise the harvest](https://lesfruitsdefendus.readthedocs.io/fr/latest/harvest-guide/supervise-harvest.html)
- [ ] [What to do in difficult situations?](https://lesfruitsdefendus.readthedocs.io/fr/latest/harvest-guide/difficult-situations.html)
- [ ] [Deliver the fruits to the beneficiary and return the equipment to the storage site](https://lesfruitsdefendus.readthedocs.io/fr/latest/harvest-guide/complete-the-pick.html)
- [ ] [Record your pick data in Saskatoon](https://lesfruitsdefendus.readthedocs.io/fr/latest/harvest-guide/record-data-in-saskatoon.html)
- [ ] [Annexes](https://lesfruitsdefendus.readthedocs.io/fr/latest/harvest-guide/annexes/index.html)
- [ ] [Information on bike safety and the trailer](https://lesfruitsdefendus.readthedocs.io/fr/latest/harvest-guide/annexes/1-bike-safety.html)
- [ ] [Ladder Security](https://lesfruitsdefendus.readthedocs.io/fr/latest/harvest-guide/annexes/2-ladder-security.html)
- [ ] [Complementary information - Health and security](https://lesfruitsdefendus.readthedocs.io/fr/latest/harvest-guide/annexes/3-complementary-infos.html)
- [ ] [Contacting other members of the collective](https://lesfruitsdefendus.readthedocs.io/fr/latest/harvest-guide/annexes/5-contacting-other-members-of-the-collective.html)

**Comment by tristanlatr** [comment]
Need to re-generate the translations files first.
